### PR TITLE
Changed logging path and fixed multiple user using rmpc issue

### LINKED ISSUE #414: Can't log to /tmp/rmpc.log from multiple users
### Description

/tmp/rmpc.log has owner of first user to run rmpc, and any users who run it later get log spam about not being able to write to it.

Ideal fix would be to log to `/tmp/rmpc_${UID}.log` or to `$XDG_RUNTIME_DIR/rmpc.log`

### Steps to reproduce

Create two users, different UID, etc.

Start rmpc as the first user, then start it as the second user. Second user can't view rmpc, because the terminal is taken up by error spam about not having access to /tmp/rmpb.log.

### Expected behavior

_No response_

### What terminal emulator are you running rmpc in?

_No response_

### rmpc debuginfo

<details>
  <summary>rmpc debuginfo</summary>

  ```sh
Not relevant
  ```
</details>

### Config file

<details>
  <summary>rmpc config</summary>

  ```ron
Not  important
  ```
</details>

### Relevant log output

<details>
  <summary>rmpc log</summary>

  ```
[flexi_logger][ERRCODE::Write] writing failed, caused by Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
[flexi_logger][ERRCODE::Write] writing failed, caused by Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
[flexi_logger][ERRCODE::Write] writing failed, caused by Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
[flexi_logger][ERRCODE::Write] writing failed, caused by Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
[flexi_logger][ERRCODE::Write] writing failed, caused by Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
[flexi_logger][ERRCODE::Write] writing failed, caused by Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
[flexi_logger][ERRCODE::Write] writing failed, caused by Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
  ```
</details>

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
## Description
- The logs are now stored in  `/tmp/rmpc_${UID}.log`  rather than  `/tmp/rmpc.log` , which will not cause any permission issues as each user will have the file with their own UID

### Related issues
- Closes #414 

### Checklist

- [x] All tests passed
- [x] Code has been formatted with nightly
- [x] Code has been checked with clippy (stable)
- [x] Documentation has been updated (if needed)
- [x] Changelog has been updated

### CODE REVIEW

**Comment by Thunder-Blaze** [comment]
I was unsure whether to use libc or read directly from /proc, but decided against adding libc as a dependency just for something that simple.

File: src/shared/logging.rs [hunk 1]
```diff
@@ -4,6 +4,15 @@ use flexi_logger::{FileSpec, FlexiLoggerError, LoggerHandle};
 use super::events::Level;
 use crate::AppEvent;
 
+pub fn get_uid() -> Option<String> {
+    std::fs::read_to_string("/proc/self/status")
```
Comment (mierak) [inline src/shared/logging.rs:8]: we already depend on rustix, why not `rustix::process::geteuid()`?

**Comment by mierak** [comment]
Thanks for remembering the issue template, I would have forgotten :smile:.
